# Generated by Django 4.1.7 on 2023-09-02 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='Алания', max_length=255, null=True, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='Турция', max_length=255, null=True, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Facility_infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wireless_Internet', models.BooleanField(verbose_name='Беспроводной интернет')),
                ('billiard', models.BooleanField(verbose_name='Бильярд')),
                ('electric_generator', models.BooleanField(verbose_name='Электрогенератор')),
                ('Ggreen_Garden', models.BooleanField(verbose_name='Зеленый сад')),
                ('finnish_sauna', models.BooleanField(verbose_name='Финская сауна')),
                ('jacuzzi', models.BooleanField(verbose_name='Джакузи')),
                ('playground', models.BooleanField(verbose_name='Детская площадка')),
                ('video_surveillance', models.BooleanField(verbose_name='Видеонаблюдение')),
                ('table_tennis', models.BooleanField(verbose_name='Настольный теннис')),
                ('indoor_swimming_pool', models.BooleanField(verbose_name='Закрытый бассейн')),
                ('roman_Steam_Room', models.BooleanField(verbose_name='Римская парная')),
                ('satellite_TV', models.BooleanField(verbose_name='Спутниковое ТВ')),
                ('massage_rooms', models.BooleanField(verbose_name='Массажные кабинеты')),
                ('fitness_center', models.BooleanField(verbose_name='Фитнес центр')),
                ('turkish_hamam', models.BooleanField(verbose_name='Турецкий хамам')),
                ('play_room', models.BooleanField(verbose_name='Игровая комната')),
                ('children_pool', models.BooleanField(verbose_name='Детский бассейн')),
                ('outdoor_swimming_pool', models.BooleanField(verbose_name='Открытый бассейн')),
                ('gazebos_for_recreation', models.BooleanField(verbose_name='Беседки для отдыха')),
                ('covered_parking', models.BooleanField(verbose_name='Крытая парковка')),
                ('outdoor_parking', models.BooleanField(verbose_name='Открытая парковка')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=255, verbose_name='От кого предложение')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.CharField(max_length=255, verbose_name='Количество комнат')),
            ],
        ),
        migrations.CreateModel(
            name='Type_real_estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_real_estate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип недвижимости')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название объекта')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена конкретного объекта')),
                ('price_one', models.IntegerField(blank=True, null=True, verbose_name='Введите цену ОТ')),
                ('price_two', models.IntegerField(blank=True, null=True, verbose_name='Введите цену ДО')),
                ('square', models.FloatField(blank=True, null=True, verbose_name='Введите площад конкретного объекта')),
                ('square_one', models.FloatField(blank=True, null=True, verbose_name='Введите площад конкретного объекта')),
                ('square_two', models.FloatField(blank=True, null=True, verbose_name='Введите площад конкретного объекта')),
                ('year_of_construction', models.DateField(blank=True, null=True, verbose_name='Введите год постройки')),
                ('furniture', models.BooleanField(blank=True, null=True, verbose_name='Если есть мебель - отметье')),
                ('to_sea', models.SmallIntegerField(blank=True, null=True, verbose_name='Введите расстояние до моря')),
                ('to_center', models.SmallIntegerField(blank=True, null=True, verbose_name='Введите расстояние до центра')),
                ('to_airport', models.SmallIntegerField(blank=True, null=True, verbose_name='Введите расстояние до аэропорта')),
                ('description', models.CharField(max_length=15000, verbose_name='Описание объекта')),
                ('main_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_city', to='flat.city')),
                ('main_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_country', to='flat.country')),
                ('main_facility_infrastructure', models.ManyToManyField(to='flat.facility_infrastructure')),
                ('main_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_offer', to='flat.offer')),
                ('main_rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_rooms', to='flat.rooms')),
                ('main_type_real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_type_real_estate', to='flat.type_real_estate')),
            ],
        ),
    ]
