# Generated by Django 4.1.7 on 2023-09-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': 'Объект недвижимости', 'verbose_name_plural': 'Объекты недвижимости'},
        ),
        migrations.AddField(
            model_name='flat',
            name='slug',
            field=models.SlugField(default='/', max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
