# Generated by Django 4.1.7 on 2023-09-02 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0002_alter_flat_options_flat_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': ' Объект недвижимости', 'verbose_name_plural': ' Объекты недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'От кого пердложение', 'verbose_name_plural': 'От кого предложения'},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterModelOptions(
            name='type_real_estate',
            options={'verbose_name': 'Тип недвижимости', 'verbose_name_plural': 'Типы недвижимости'},
        ),
        migrations.RemoveField(
            model_name='flat',
            name='main_facility_infrastructure',
        ),
        migrations.AddField(
            model_name='flat',
            name='Ggreen_Garden',
            field=models.BooleanField(default=True, verbose_name='Зеленый сад'),
        ),
        migrations.AddField(
            model_name='flat',
            name='billiard',
            field=models.BooleanField(default=True, verbose_name='Бильярд'),
        ),
        migrations.AddField(
            model_name='flat',
            name='children_pool',
            field=models.BooleanField(default=True, verbose_name='Детский бассейн'),
        ),
        migrations.AddField(
            model_name='flat',
            name='covered_parking',
            field=models.BooleanField(default=True, verbose_name='Крытая парковка'),
        ),
        migrations.AddField(
            model_name='flat',
            name='electric_generator',
            field=models.BooleanField(default=True, verbose_name='Электрогенератор'),
        ),
        migrations.AddField(
            model_name='flat',
            name='finnish_sauna',
            field=models.BooleanField(default=True, verbose_name='Финская сауна'),
        ),
        migrations.AddField(
            model_name='flat',
            name='fitness_center',
            field=models.BooleanField(default=True, verbose_name='Фитнес центр'),
        ),
        migrations.AddField(
            model_name='flat',
            name='gazebos_for_recreation',
            field=models.BooleanField(default=True, verbose_name='Беседки для отдыха'),
        ),
        migrations.AddField(
            model_name='flat',
            name='indoor_swimming_pool',
            field=models.BooleanField(default=True, verbose_name='Закрытый бассейн'),
        ),
        migrations.AddField(
            model_name='flat',
            name='jacuzzi',
            field=models.BooleanField(default=True, verbose_name='Джакузи'),
        ),
        migrations.AddField(
            model_name='flat',
            name='massage_rooms',
            field=models.BooleanField(default=True, verbose_name='Массажные кабинеты'),
        ),
        migrations.AddField(
            model_name='flat',
            name='outdoor_parking',
            field=models.BooleanField(default=True, verbose_name='Открытая парковка'),
        ),
        migrations.AddField(
            model_name='flat',
            name='outdoor_swimming_pool',
            field=models.BooleanField(default=True, verbose_name='Открытый бассейн'),
        ),
        migrations.AddField(
            model_name='flat',
            name='play_room',
            field=models.BooleanField(default=True, verbose_name='Игровая комната'),
        ),
        migrations.AddField(
            model_name='flat',
            name='playground',
            field=models.BooleanField(default=True, verbose_name='Детская площадка'),
        ),
        migrations.AddField(
            model_name='flat',
            name='roman_Steam_Room',
            field=models.BooleanField(default=True, verbose_name='Римская парная'),
        ),
        migrations.AddField(
            model_name='flat',
            name='satellite_TV',
            field=models.BooleanField(default=True, verbose_name='Спутниковое ТВ'),
        ),
        migrations.AddField(
            model_name='flat',
            name='table_tennis',
            field=models.BooleanField(default=True, verbose_name='Настольный теннис'),
        ),
        migrations.AddField(
            model_name='flat',
            name='turkish_hamam',
            field=models.BooleanField(default=True, verbose_name='Турецкий хамам'),
        ),
        migrations.AddField(
            model_name='flat',
            name='video_surveillance',
            field=models.BooleanField(default=True, verbose_name='Видеонаблюдение'),
        ),
        migrations.AddField(
            model_name='flat',
            name='wireless_Internet',
            field=models.BooleanField(default=True, verbose_name='Беспроводной интернет'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='main_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_city', to='flat.city', verbose_name='Выберите город'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='main_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_country', to='flat.country', verbose_name='Выберите страну'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='main_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_offer', to='flat.offer', verbose_name='Укажите от кого предложение'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='main_rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_rooms', to='flat.rooms', verbose_name='Выберите комнаты'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='main_type_real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_type_real_estate', to='flat.type_real_estate', verbose_name='Выберите тип недвижимости'),
        ),
        migrations.DeleteModel(
            name='Facility_infrastructure',
        ),
    ]
