# Generated by Django 4.1.7 on 2023-09-02 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0003_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='description',
            field=models.TextField(max_length=15000, verbose_name='Описание объекта'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='title',
            field=models.CharField(help_text='Основное название объекта', max_length=255, unique=True, verbose_name='Название объекта'),
        ),
    ]
