# Generated by Django 4.1.7 on 2023-09-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0004_flat_created_at_alter_city_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'От кого пердложение', 'verbose_name_plural': 'От кого предложение'},
        ),
        migrations.RemoveField(
            model_name='flat',
            name='price_one',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='price_two',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='square_one',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='square_two',
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.IntegerField(blank=True, help_text='EURO', null=True, verbose_name='Цена объекта'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='square',
            field=models.FloatField(blank=True, help_text='m2', null=True, verbose_name='Площадь объекта'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='to_airport',
            field=models.FloatField(blank=True, help_text='Пример (8.9)', null=True, verbose_name='Расстояние до аэропорта в киллометрах'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='to_center',
            field=models.FloatField(blank=True, help_text='Пример (2.2)', null=True, verbose_name='Расстояние до центра в киллометрах'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='to_sea',
            field=models.FloatField(blank=True, help_text='Пример (0.2)', null=True, verbose_name='Расстояние до моря в киллометрах'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='year_of_construction',
            field=models.SmallIntegerField(blank=True, help_text='Пример 2023', null=True, verbose_name='Год постройки'),
        ),
    ]
