# Generated by Django 4.1.7 on 2023-09-29 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0005_district_alter_offer_options_remove_flat_price_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='main_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_district', to='flat.district', verbose_name='Район'),
        ),
    ]
