# Generated by Django 4.1.7 on 2023-09-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0007_flat_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='main_rooms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_rooms', to='flat.rooms', verbose_name='Выберите комнаты'),
        ),
    ]
