# Generated by Django 4.1.7 on 2023-09-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0008_alter_flat_main_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
