# Generated by Django 4.1.7 on 2023-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0010_flat_first_line_flat_hot_offer_flat_out_infra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('text', models.TextField(max_length=15000, verbose_name='Текст отзыва')),
                ('data', models.CharField(help_text='Введите дату в формате 01.01.2021', max_length=100, verbose_name='Дата')),
                ('photo', models.ImageField(blank=True, upload_to='media/reviews/%Y/%m/', verbose_name='Фото')),
            ],
        ),
    ]
