# Generated by Django 4.1.7 on 2023-10-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0014_laws'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='Ggreen_Garden',
            new_name='Green_Garden',
        ),
        migrations.AlterField(
            model_name='flat',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='title',
            field=models.CharField(help_text='Основное название объекта', max_length=255, verbose_name='Название объекта'),
        ),
    ]
