# Generated by Django 4.1.7 on 2023-10-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0015_rename_ggreen_garden_flat_green_garden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 1'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='main_photo',
            field=models.ImageField(default=0, upload_to='media/flat/%Y/%m/', verbose_name='Главное фото'),
            preserve_default=False,
        ),
    ]
