# Generated by Django 4.1.7 on 2023-10-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0016_flat_photo1_flat_photo2_flat_photo3_flat_photo4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='photo10',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 10'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo11',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 11'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo12',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 12'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo13',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 13'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo14',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 14'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo15',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 15'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo16',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 16'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo17',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 17'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo18',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 18'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo19',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 19'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo20',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 20'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo21',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 21'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo22',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 22'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo23',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 23'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo24',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 24'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo25',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 25'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo26',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 26'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo27',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 27'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo28',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 28'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo29',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 29'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo30',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 30'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo31',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 31'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo32',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 32'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo33',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 33'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo34',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 34'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo35',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 35'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 5'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 6'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo7',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 7'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo8',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 8'),
        ),
        migrations.AddField(
            model_name='flat',
            name='photo9',
            field=models.ImageField(blank=True, null=True, upload_to='media/flat/add_photo/%Y/%m/', verbose_name='Фото 9'),
        ),
    ]
