# Generated by Django 4.1.7 on 2023-10-09 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0017_flat_photo10_flat_photo11_flat_photo12_flat_photo13_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='main_type_real_estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_type_real_estate', to='flat.type_real_estate', verbose_name='Выберите тип недвижимости'),
        ),
    ]
