# Generated by Django 4.1.7 on 2023-10-09 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0018_alter_flat_main_type_real_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='main_type_real_estate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_type_real_estate', to='flat.type_real_estate', verbose_name='Выберите тип недвижимости'),
            preserve_default=False,
        ),
    ]
