# Generated by Django 4.1.7 on 2023-10-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0020_contact_alter_flat_description_alter_flat_main_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='text_ar',
            field=models.TextField(max_length=25000, null=True, verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='articles',
            name='text_en',
            field=models.TextField(max_length=25000, null=True, verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='articles',
            name='text_fa',
            field=models.TextField(max_length=25000, null=True, verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='articles',
            name='text_ru',
            field=models.TextField(max_length=25000, null=True, verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='articles',
            name='text_tr',
            field=models.TextField(max_length=25000, null=True, verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='district',
            name='district_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='district',
            name='district_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='district',
            name='district_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='district',
            name='district_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='district',
            name='district_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='flat',
            name='description_ar',
            field=models.TextField(help_text='Обязательное поле', max_length=15000, null=True, verbose_name='Описание объекта'),
        ),
        migrations.AddField(
            model_name='flat',
            name='description_en',
            field=models.TextField(help_text='Обязательное поле', max_length=15000, null=True, verbose_name='Описание объекта'),
        ),
        migrations.AddField(
            model_name='flat',
            name='description_fa',
            field=models.TextField(help_text='Обязательное поле', max_length=15000, null=True, verbose_name='Описание объекта'),
        ),
        migrations.AddField(
            model_name='flat',
            name='description_ru',
            field=models.TextField(help_text='Обязательное поле', max_length=15000, null=True, verbose_name='Описание объекта'),
        ),
        migrations.AddField(
            model_name='flat',
            name='description_tr',
            field=models.TextField(help_text='Обязательное поле', max_length=15000, null=True, verbose_name='Описание объекта'),
        ),
        migrations.AddField(
            model_name='flat',
            name='title_ar',
            field=models.CharField(help_text='Обязательное поле', max_length=255, null=True, verbose_name='Название объекта'),
        ),
        migrations.AddField(
            model_name='flat',
            name='title_en',
            field=models.CharField(help_text='Обязательное поле', max_length=255, null=True, verbose_name='Название объекта'),
        ),
        migrations.AddField(
            model_name='flat',
            name='title_fa',
            field=models.CharField(help_text='Обязательное поле', max_length=255, null=True, verbose_name='Название объекта'),
        ),
        migrations.AddField(
            model_name='flat',
            name='title_ru',
            field=models.CharField(help_text='Обязательное поле', max_length=255, null=True, verbose_name='Название объекта'),
        ),
        migrations.AddField(
            model_name='flat',
            name='title_tr',
            field=models.CharField(help_text='Обязательное поле', max_length=255, null=True, verbose_name='Название объекта'),
        ),
        migrations.AddField(
            model_name='laws',
            name='text_ar',
            field=models.TextField(max_length=25000, null=True, verbose_name='Текст новости'),
        ),
        migrations.AddField(
            model_name='laws',
            name='text_en',
            field=models.TextField(max_length=25000, null=True, verbose_name='Текст новости'),
        ),
        migrations.AddField(
            model_name='laws',
            name='text_fa',
            field=models.TextField(max_length=25000, null=True, verbose_name='Текст новости'),
        ),
        migrations.AddField(
            model_name='laws',
            name='text_ru',
            field=models.TextField(max_length=25000, null=True, verbose_name='Текст новости'),
        ),
        migrations.AddField(
            model_name='laws',
            name='text_tr',
            field=models.TextField(max_length=25000, null=True, verbose_name='Текст новости'),
        ),
        migrations.AddField(
            model_name='laws',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='laws',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='laws',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='laws',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='laws',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ar',
            field=models.TextField(max_length=25000, null=True, verbose_name='Текст новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=models.TextField(max_length=25000, null=True, verbose_name='Текст новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_fa',
            field=models.TextField(max_length=25000, null=True, verbose_name='Текст новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=models.TextField(max_length=25000, null=True, verbose_name='Текст новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_tr',
            field=models.TextField(max_length=25000, null=True, verbose_name='Текст новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='От кого предложение'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_en',
            field=models.CharField(max_length=255, null=True, verbose_name='От кого предложение'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='От кого предложение'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='От кого предложение'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='От кого предложение'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_ar',
            field=models.TextField(max_length=15000, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_en',
            field=models.TextField(max_length=15000, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_fa',
            field=models.TextField(max_length=15000, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_ru',
            field=models.TextField(max_length=15000, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_tr',
            field=models.TextField(max_length=15000, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='type_real_estate',
            name='type_real_estate_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип недвижимости'),
        ),
        migrations.AddField(
            model_name='type_real_estate',
            name='type_real_estate_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип недвижимости'),
        ),
        migrations.AddField(
            model_name='type_real_estate',
            name='type_real_estate_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип недвижимости'),
        ),
        migrations.AddField(
            model_name='type_real_estate',
            name='type_real_estate_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип недвижимости'),
        ),
        migrations.AddField(
            model_name='type_real_estate',
            name='type_real_estate_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип недвижимости'),
        ),
    ]
