# Generated by Django 4.1.7 on 2023-10-17 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0022_city_city_ar_city_city_en_city_city_fa_city_city_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Инфраструктура')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Инфраструктура')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Инфраструктура')),
                ('title_tr', models.CharField(max_length=255, null=True, verbose_name='Инфраструктура')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='Инфраструктура')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='Инфраструктура')),
            ],
            options={
                'verbose_name': 'Инфраструктура',
                'verbose_name_plural': 'Инфраструктура',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Статус')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Статус')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Статус')),
                ('title_tr', models.CharField(max_length=255, null=True, verbose_name='Статус')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='Статус')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AddField(
            model_name='flat',
            name='main_infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_infrastructure', to='flat.infrastructure', verbose_name='Инфраструктура'),
        ),
        migrations.AddField(
            model_name='flat',
            name='main_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_status', to='flat.status', verbose_name='Статус'),
        ),
    ]
